[package]
name = "net_battle_server"
version = "0.1.0"
authors = ["Arthur <arthurcose@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
byteorder = "1.4.2"
uuid = { version = "0.8.2", features = ["v4"] }
rlua = "0.17.0"
paste = "1.0.4"
clap = "2.33.3"
